name: Deploy pages

on:
  workflow_dispatch:
  repository_dispatch:
    types: [update_content]

jobs:
  build:
    runs-on: ubuntu-20.04
  
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v3.1.3
        with:
          python-version: 3.11.1
      
      - name: Install dependencies
        run: |
          cd ./ssg
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv lock
          pipenv sync --dev
      
      - name: Build
        run: |
          pipenv run python ./html.py
      
      - name: Push docs
        run: |
          git config --global user.name "pishiko"
          git config --global user.email "pishiko@users.noreply.github.com"
          if (git diff --shortstat | grep '[0-9]'); then \
            git add docs; \
            git commit -m "github action push"; \
            git push; \
          fi
      
